# Demo 2.2 Indexing and Slicing Arrays
- Demonstrates how to:  
  - Load a dataset with numpy
  - Extract a subset of the data using indexing and slicing 
  - Calculate the summary statistics of the data 

** requires data files: `grades.csv`

---

In [1]:
import numpy as np

# Part 1

In [3]:
# 1. Load the dataset, grades.csv, using numpy's genfromtxt() function. 
# Skip the header row.
# Then, Extract the columns for Math, Science, and English from the dataset and 
# store them in separate variables named `grades_math`, `grades_science`, and `grades_english`.
# Print the arrays as output. 

# YOUR CODE HERE

[85. 78. 92. 75. 88. 84. 90. 76.]
[90. 85. 88. 80. 92. 87. 85. 80.]
[88. 84. 91. 78. 89. 86. 88. 82.]


# Part 2


In [ ]:
# 1. Extract the grades for the first three students in Math and Science and 
# store them in the variable,`grades_first_three_math_science`.

# YOUR CODE HERE


[[85. 90.]
 [78. 85.]
 [92. 88.]]


# Part 3: Identify the Summary Statistics:

In [13]:
# 1. Calculate the mean, median, standard deviation, minimum, and maximum of the grades for Math, 
# Science, and English.

# YOUR CODE HERE

Math - Mean: 83.5, Median: 84.5, Std: 6.082762530298219, Min: 75.0, Max: 92.0
Science - Mean: 85.875, Median: 86.0, Std: 4.044672421840859, Min: 80.0, Max: 92.0
English - Mean: 85.75, Median: 87.0, Std: 3.960744879438715, Min: 78.0, Max: 91.0
