# Demo 2.2 Indexing and Slicing Arrays
- Demonstrates how to:  
  - Load a dataset with numpy
  - Extract a subset of the data using indexing and slicing 
  - Calculate the summary statistics of the data 

** requires data files: `grades.csv`

---

In [1]:
import numpy as np

# Part 1

In [11]:
# 1. Load the dataset, grades.csv, using numpy's genfromtxt() function. 
# Skip the header row.
# Then, Extract the columns for Math, Science, and English from the dataset and 
# store them in separate variables named `grades_math`, `grades_science`, and `grades_english`.
# Print the arrays as output. 

# Load the dataset
data = np.genfromtxt('grades.csv', delimiter=',', skip_header=1)

# Extract the columns for Math, Science, and English
grades_math = data[:, 1]
grades_science = data[:, 2]
grades_english = data[:, 3]

# Print the arrays
print(grades_math)
print(grades_science)
print(grades_english)


[85. 78. 92. 75. 88. 84. 90. 76.]
[90. 85. 88. 80. 92. 87. 85. 80.]
[88. 84. 91. 78. 89. 86. 88. 82.]


# Part 2


In [18]:
# 1. Extract the grades for the first three students in Math and Science and 
# store them in the variable,`grades_first_three_math_science`.

# Extract the grades for the first three students in Math and Science
grades_first_three_math_science = data[:3, 1:3]
print(grades_first_three_math_science)


[[85. 90.]
 [78. 85.]
 [92. 88.]]


# Part 3: Identify the Summary Statistics:

In [20]:
# 1. Calculate the mean, median, standard deviation, minimum, and maximum of the grades for Math, 
# Science, and English.

# Calculate the mean, median, standard deviation, minimum, and maximum of the grades for Math
mean_math = np.mean(grades_math)
median_math = np.median(grades_math)
std_math = np.std(grades_math)
min_math = np.min(grades_math)
max_math = np.max(grades_math)

# print the output
print("Mean:", mean_math)
print("Median:", median_math)
print("Standard Deviation:", std_math)
print("Minimum:", min_math)
print("Maximum:", max_math)


Mean: 83.5
Median: 84.5
Standard Deviation: 6.082762530298219
Minimum: 75.0
Maximum: 92.0
