# Ex 2.1 Using NumPy Statistics Functions
- Demonstrates how to:
  - Identify the shape and type of a NumPy array.  
  - Use NumPy statistics functions, including peak to peak (ptp), amax, and average.

---

In [1]:
import numpy as np

### A 2D NumPy Array of base salary over three months:

In [7]:
jeff_salary = [2700, 3000, 3000]
nick_salary = [2600, 2800, 2800]
tom_salary = [2300, 2500, 2500]
base_salary = np.array([jeff_salary, nick_salary, tom_salary])
print(base_salary)

[[2700 3000 3000]
 [2600 2800 2800]
 [2300 2500 2500]]


### A 2D NumPy Array containing the employees' monthly bonuses:

In [12]:
jeff_bonus = [500, 400, 400]
nick_bonus = [600, 300, 400]
tom_bonus = [200, 500, 400]
bonus = np.array([jeff_bonus, nick_bonus, tom_bonus])
print(bonus)

[[500 400 400]
 [600 300 400]
 [200 500 400]]


---

# Part 1

In [19]:
# 1. Identify the shape of the base_salary and bonus arrays.
# Use the .shape attribute to identify the shape of the base_salary and bonus arrays.

print(f"Base salary shape: {base_salary.shape}")
print(f"Bonus shape: {bonus.shape}")

Base salary shape: (3, 3)
Bonus shape: (3, 3)


---

# Part 2

- Documentation for the numpy.ptp function can be found at: [numpy.ptp](https://numpy.org/doc/stable/reference/generated/numpy.ptp.html)

In [22]:
# 1. Find the difference between the highest and lowest base salary for each period and print the result.
# Use the numpy.ptp() function that calculates a range of values (maximum - minimum) 
# along the 0 axis to identify the result. 

print(f"Difference between the highest and lowest base salary for each period: {np.ptp(base_salary, axis=0)}")

Difference between the highest and lowest base salary for each period: [400 500 500]


---

# Part 3
- Each result set returned by `np.amax()`, as shown in our course notebook example is itself a NumPy array. Therefore, we can pass the result set to any other NumPy statistical function.
- Use the `np.average()` function to calculate the average of the maximum amounts paid each month to all employees.
    - Documentation for the numpy.average function can be found at: [numpy.average](https://numpy.org/doc/stable/reference/generated/numpy.average.html)

In [25]:
# 1. Use the np. average() and np.amax functions to 
# calculate the average of the maximum amounts paid each month to all employees.

print(f"Average of the maximum amounts paid each month to all employees: {np.average(np.amax(base_salary + bonus, axis=0))}")

Average of the maximum amounts paid each month to all employees: 3333.3333333333335
